# Generated by Django 6.0.3 on 2026-03-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('credit', 'Credito'), ('debit', 'Debito'), ('qr', 'QR'), ('other', 'Otro')], default='', max_length=20, verbose_name='Metodo de Pago'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='', max_length=10, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('preparing', 'Preparando'), ('ready', 'Listo'), ('delivered', 'Entregado'), ('paid', 'Cobrado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
